WorldBuilder/WorldBuilder/Controllers/CharacterController.cs
using System.Web.Mvc;
using WorldBuilder.Helpers.Factories;
using WorldBuilder.ViewModels;

namespace WorldBuilder.Controllers
{
    public class CharacterController : Controller
    {
        private readonly ICharacterFactory characterFactory;

        public CharacterController(ICharacterFactory characterFactory)
        {
            this.characterFactory = characterFactory;
        }

        public ActionResult Index()
        {
            var viewModel = characterFactory.CreateCharacterViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult CreateCharacter(CharacterViewModel viewModel)
        {
            characterFactory.CreateCharacter(viewModel);
            return Redirect("Index");
        }

        public ActionResult CharacterProfile(int id)
        {
            var viewModel = characterFactory.GetCharacter(id);
            return View(viewModel);
        }

        public ActionResult CharacterList()
        {
            var viewModel = characterFactory.GetAllCharacters();
            return View(viewModel);
        }

        public ActionResult EditCharacterProfile(int id)
        {
            var viewModel = characterFactory.GetCharacter(id);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditCharacter(CharacterViewModel viewModel)
        {
            characterFactory.UpdateCharacter(viewModel);
            return Redirect(string.Format("CharacterProfile/{0}",viewModel.Id));
        }
    }
}

WorldBuilder/WorldBuilder/Controllers/WorldController.cs
using System.Web.Mvc;
using WorldBuilder.Helpers.Factories;
using WorldBuilder.ViewModels;

namespace WorldBuilder.Controllers
{
    public class WorldController : Controller
    {

        private readonly ILocationFactory locationFactory;

        public WorldController(ILocationFactory locationFactory)
        {
            this.locationFactory = locationFactory;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateLocation()
        {
            return View(new LocationViewModel());
        }

        [HttpPost]
        public ActionResult CreateLocation(LocationViewModel viewModel)
        {
            locationFactory.SaveLocation(viewModel);
            return Redirect("Index");
        }

        public ActionResult Location(int id)
        {
            var viewModel = locationFactory.GetLocation(id);
            return View(viewModel);
        }
    }
}

WorldBuilder/WorldBuilder/Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="container">
        <ul>
            <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Characters", "CharacterList", "Character")</li>
        </ul>
    </div>
</footer>

WorldBuilder/WorldBuilder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dustvale - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @Html.Partial("_NavBar")
    @RenderBody()
    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WorldBuilder/WorldBuilder/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            @*TODO Add icon here*@
            @if (Request.IsAuthenticated)
            {
                <li>@Html.ActionLink("Home", "Index", "World")</li>
                <input class="search" placeholder="Search" />
                <submit class="btn">Go</submit>
            }
            @if (User.IsInRole("Admin"))
            {
                <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
            }
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</div>